### ISSUE TITLE
User can de-select all templates

### ISSUE THREAD

**Issue by glen** [snehaq/MailSenderApplication#3]
A User can de-select all the templates and save. This throws an exception

SEVERE: Servlet.service() for servlet [controller.Controller] in context with path [/MailSendingApplication] threw exception
java.lang.NullPointerException
	at controller.Controller.setTemplatesInProperties(Controller.java:284)
	at controller.Controller.doPost(Controller.java:158)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)

**Comment by snehaq** [comment]
we have fixed the issue.There has to be atleast one template checked.

**Comment by glen** [comment]
Verified that user cannot de-select all the templates.
